### ISSUE TITLE
Demo appears broken?  Only one window spawns a player.. 

### ISSUE THREAD

**Issue by manthrax** [hathora/bullet-mania#4]
and the controls seem bit lagged?

**Comment by hpx7** [comment]
Once a game loads, you have to open another window with the same URL (the roomId gets appended to the url).

For example hathora-topdown-shooter.surge.sh/asdfasdfa (where `asdfasdfa` is the roomId which is automatically added once the game loads)

**Comment by manthrax** [comment]
That.. .sorta works.. I open the second window, and I can control the character in the first window? But the second window has no character? Is that by design?

**Comment by hpx7** [comment]
Hmm I can control both characters:
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/5400947/192881299-b4d77ebc-5748-4691-a242-8affc4db0347.png">

Could you record a gif and upload?

**Comment by hpx7** [comment]
Ah if you use Right Click ->  Duplicate in Chrome then it doesn't work because Chrome copies over the `sessionStorage`, which makes you have the same user on the second tab. Try opening a new tab (or window) first then copy/pasting the url instead

**Comment by manthrax** [comment]
Tried with cut and paste.. same issue. Does the documentation cover this?

**Comment by hpx7** [comment]
And you're not using the Duplicate functionality in Chrome? And you are using Chrome right? That's very strange, would love to see a gif to try and understand better.

Can you also try with two separate windows?
